example cli project

diff --git a/cljmd b/cljmd
--- a/cljmd
+++ b/cljmd
@@ -1,4 +1,5 @@
 #!/usr/bin/env bash
+CLJ_OPTS='-J-Xms256m -J-Xmx256m -J-client'
 hash clojure 2>/dev/null || { echo >&2 'Clojure tools not found. Refer https://clojure.org/guides/deps_and_cli'; exit 1; }
 
 args='['
@@ -36,11 +37,107 @@ if test -f "$1"; then
 
 (def ^:dynamic *cmdjure-version* "0.0.3")
 (def ^:dynamic *cwd* (System/getProperty "user.dir"))
-(def ^:dynamic *script* "$1")
+(def ^:dynamic *script* (seq "$1"))
 
 (binding [*command-line-args* $args]
   (load-file *script*))
 EOF
 	DEPS='{:deps {com.cemerick/pomegranate {:mvn/version "1.1.0"}}}'
-	exec clojure -J-Xms256m -J-Xmx256m -J-client -Sdeps "$DEPS" -e "$clj_script"
+	exec clojure $CLJ_OPTS -Sdeps "$DEPS" -e "$clj_script"
+else
+	config_file=$HOME/.cljmd
+
+	PROGNAME=$(basename $0)
+	error_exit() {
+		echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
+		exit 1
+	}
+
+	sed_escape() {
+		sed -e 's/[]\/$*.^[]/\\&/g'
+	}
+
+	cfg_write() { # key, value
+		cfg_delete "$config_file" "$1"
+		echo "$1=$2" >> "$config_file"
+	}
+
+	cfg_read() { # key -> value
+		test -f "$config_file" && grep "^$(echo "$1" | sed_escape)=" "$config_file" | sed "s/^$(echo "$1" | sed_escape)=//" | tail -1
+	}
+
+	cfg_delete() { # key
+		test -f "$config_file" && sed -i "/^$(echo $1 | sed_escape).*$/d" "$config_file"
+	}
+
+	cfg_haskey() { # key
+		test -f "$config_file" && grep "^$(echo "$1" | sed_escape)=" "$config_file" > /dev/null
+	}
+
+	repo_root=$(cfg_read repository)
+	[[ -z "$repo_root" ]] && error_exit "'repository' config value not found."
+	repo_dir="$repo_root/repository"
+
+	declare -A clis
+	namespaces=$(cfg_read discovery_namespaces)
+	repo_dir_str_length=$((${#repo_dir} + 1))
+
+	discover_clis() {
+		[[ -z "$namespaces" ]] && error_exit "'discovery_namespaces' config value not found."
+		namespaces=(${namespaces//,/ })
+		for i in ${!namespaces[@]};do
+			namespaces[$i]="${repo_dir}/${namespaces[$i]//./\/}"
+		done
+		local artifacts=$(find ${namespaces[@]} -name *.jar | tac)
+		for artifact in ${artifacts}; do
+			local artifact="${artifact:$repo_dir_str_length}"
+			local groupId=$(echo "$artifact" | rev | cut -d/ -f4- | rev | tr / .)
+			local artifactId=$(echo "$artifact" | awk -F/ '{print $(NF-2)}')
+			local version=$(echo "$artifact" | awk -F/ '{print $(NF-1)}')
+			local cli="$groupId/$artifactId"
+			local knownVersion=${clis["$cli"]}
+			if [[ ${version} > ${knownVersion} ]];then
+				clis["$cli"]="$version"
+			fi
+		done
+	}
+
+	list_clis() {
+		echo "Local Commands in: $repo_dir"
+		for dep in "${!clis[@]}";do
+			local artifact=$(echo "$dep" | awk -F/ '{print $NF}')
+			local version="${clis[$dep]}"
+			local pom="$repo_dir/$(echo "$dep" | tr . /)/$version/*$version.pom"
+			pom=$(realpath ${pom})
+			local groupId=$(echo ${dep} | cut -d/ -f1)
+			if test -f "$pom"; then
+				echo -e "    $artifact\t$groupId\t$version\t$(cat "$pom" | grep -oPm1 "(?<=<description>)[^<]+")"
+			fi
+		done | column -ts $'\t' | sort | cut -b -$(tput cols)
+	}
+
+	run_cli(){
+		local matched
+		for dep in "${!clis[@]}";do
+			if [[ "$dep" == */${1} ]];then
+				local version="${clis[$dep]}"
+				local groupId=$(echo ${dep} | cut -d/ -f1)
+				local ns=$(echo $dep | tr / .)
+				local DEPS="{:deps {$dep {:mvn/version \"${version}\"}}}"
+				matched=true
+				exec clojure $CLJ_OPTS -Sdeps "$DEPS" -m ${ns}.core "${@:2}"
+				break
+			fi
+		done
+		matched || error_exit "Unable to find cli '$1'. Run '$PROGNAME --list' to see a list of all available commands"
+	}
+
+	discover_clis
+
+	case $1 in
+		--list|-l)
+				list_clis;;
+			*)
+				run_cli "$1";;
+	esac
 fi
